server:
  port: 18086
spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        dashboard: localhost:8080
        port: 8719
  zipkin:
    base-url: http://localhost:9411
    sender:
      type: web
    discovery-client-enabled: true
  sleuth:
    sampler:
      probability: 1
  elasticsearch:
    rest:
      uris: http://localhost:9200
  thymeleaf:
    cache: false #关闭服务端缓存，但是在生产环境时，要记得开启

  jackson:
    default-property-inclusion: non_null #不包含空的内容
  rabbitmq:
    host: 192.168.144.131
    virtual-host: /ding
    username: ding
    password: ding
    listener:
      simple:
        concurrency: 4
        acknowledge-mode: manual
        prefetch: 1
feign:
  sentinel:
    enabled: true