server:
  port: 18084
spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        dashboard: localhost:8080
        port: 8179
    alibaba:
      seata:
        tx-service-group: gmall-tx-group
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.144.131:3306/guli_sms?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    password: root
    username: root
  redis:
    host: 192.168.144.131
  zipkin:
    base-url: http://localhost:9411
    discovery-client-enabled: true
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1
mybatis-plus:
  mapper-locations: classpath:mapper/sms/**/*.xml
  type-aliases-package: com.atguigu.gmall.sms.entity

  global-config:
    db-config:
      id-type: auto
feign:
  sentinel:
    enabled: true

