server:
  port: 18089
spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        dashboard: localhost:8080
        port: 8719
  zipkin:
    base-url: http:// localhost:9411
    sender:
      type: web
    discovery-client-enabled: false
  sleuth:
    sampler:
      probability: 1
  redis:
    host: 192.168.144.131
    thymeleaf:
      cache: false
feign:
  sentinel:
    enabled: true
auth:
  jwt:
    pubKeyPath: F:\guli-front\rsa\rsa.pub
    priKeyPath: F:\guli-front\rsa\rsa.pri
    secret: 123456abcd789efgh
    expire: 180
    cookieName: GMALL-TOKEN
    unick: unick

